openapi: 3.1.0
info:
  title: API Document
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /stats/albums/year-artist:
    get:
      summary: 연도와 가수별 앨범 수 리턴하는 API
      parameters:
        - in: query
          name: page
          description: 1-based page number
          required: false
          schema:
            type: number
            default: 1
        - in: query
          name: size
          description: page size
          required: false
          schema:
            type: number
            default: 50
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: object
                    properties:
                      year:
                        type: number
                        description: 연도
                      artist:
                        type: string
                        description: 가수
                      count:
                        type: number
                        description: 앨범 갯수

  /trending-songs:
    get:
      summary: 최근 1시간동안 "좋아요"가 많이 증가한 노래를 확인할 수 있는 API
      parameters:
        - in: query
          name: size
          description: 최대 몇 개를 리턴할 지
          required: false
          schema:
            type: number
            default: 10
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  songs:
                    type: array
                    items:
                      type: object
                      properties:
                        likes:
                          type: number
                          description: 최근 1시간 동안 받은 좋아요 갯수
                        id:
                          type: number
                          description: 노래 ID
                        title:
                          type: string
                          description: 노래 제목
                        artist:
                          type: string
                          description: 아티스트
                        releaseDate:
                          type: string
                          description: 발표일
  /songs/{song-id}/likes:
    put:
      summary: 좋아요 증가 API
      description: |
        (song_id, user_id) 기준으로 멱등적으로 동작함
      parameters:
        - in: path
          name: song-id
          description: 노래 ID
          required: true
        - in: header
          name: USER-ID
          description: 회원 ID
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
        404:
          description: |
            - 노래가 없음
          content:
            application/json:
              schema:
                type: object
